### ISSUE TITLE
geforce-game-ready-driver on Win 10 Enterprise tries to install Win 8/7 version

### ISSUE THREAD

**Issue by jaxzin** [AeliusSaionji/chocopkgs#10]
Trying to debug this and adding this to the geforce-game-ready-driver/tools/chocolateyInstall.ps1:
```
   $osversion = [System.Environment]::OSVersion
   Write-Host $osversion 
```
Returns `Microsoft Windows NT 6.2.9200.0`, but I'm running this on Windows 10 Enterprise 1511. Not sure why the subshell is returning the incorrect version of the OS.

**Comment by Link-Satonaka** [comment]
That's strange. Seems like a bug in powershell; maybe you should report that to the powershell github!

**Comment by Link-Satonaka** [comment]
@jaxzin Does the lastest version of 10 Enterprise correctly report OSVersion?
