### ISSUE TITLE
FEATURE REQUEST: Remove old extracted installation files

### ISSUE THREAD

**Issue by bcurran3** [AeliusSaionji/chocopkgs#15]
For a year plus now I've noticed that after the NVIDIA display drivers are installed I'm left with a C:\NVIDIA directory. Currently I have four old versions of the extracted installation files.

When I try to delete the folder to OCDly (I created a new word!) clean up my system volume, I get:

![image](https://user-images.githubusercontent.com/14026600/39220305-eff816ea-47e4-11e8-8f1a-c08017dc2583.png)

I can't delete it with my normal user/administrative account.

The fact it says SYSTEM is the owner might not be what everyone else gets. It might be due to the drivers being upgraded in the wee hours of the night by my https://chocolatey.org/packages/choco-upgrade-all-at package. I'm really not sure. (Someone please chime in and say if you have the same problem and if you installed manually or via Chocolatey under your normal admin account.)

It would be wonderful if you reset the permissions on the folder after install so that anyone can delete the files. It <s>might be as</s> is easy as changing the owner from SYSTEM to ADMINISTRATORS or USERS. <s>(Needs some testing.)</s>

After that a simple Remove-Item can clean up the files.

If you need help, here are some basic tutorials:
https://blogs.msdn.microsoft.com/johan/2008/10/01/powershell-editing-permissions-on-a-file-or-folder/
http://www.tomsitpro.com/articles/powershell-manage-file-system-acl,2-837.html
https://stackoverflow.com/questions/25779423/powershell-to-set-folder-permissions

Ironically I packaged this up a few months ago: https://chocolatey.org/packages/ntfssecurity-psmodule but haven't implemented it in any of my scripts yet. 😀

**Comment by bcurran3** [comment]
CONFIRMED: Changing OWNER to local ADMINISTRATOR allows easy deletion of the files.

**Comment by AeliusSaionji** [comment]
hmm, my `C:\NVIDIA` is owned by the ADMINISTRATORS group already, not SYSTEM. I could just delete mine. I wonder: is your task running chocolatey as SYSTEM somehow?

**Comment by AeliusSaionji** [comment]
Seems like the drivers don't create a `c:\NVIDIA` folder anymore? You might be interested to know that NVIDIA does leave a significant chunk of files in `C:\Program Files\NVIDIA Corporation\Installer2`, and Windows itself holds on to previous versions of the driver (which can consume multiple GB) somewhere in the WINDOWS folder. You might want to keep those around since they are used in system restore, but you can use something like https://github.com/lostindark/DriverStoreExplorer to purge those.

Anyway, closing this.

**Comment by bcurran3** [comment]
HEY! Thanks. It looks like you're right. The last set of drivers in my \NVIDIA directory are 397.41 whilst I've got 419.67 installed.

Now to go delete them... for good!

p.s.

> hmm, my C:\NVIDIA is owned by the ADMINISTRATORS group already, not SYSTEM. I could just delete mine. I wonder: is your task running chocolatey as SYSTEM somehow?

Yes. my CUP ALL runs every morning at 2AM via SYSTEM account.
