### ISSUE TITLE
(nvidia-display-driver) Need a DCH package.

### ISSUE THREAD

**Issue by crkinard** [AeliusSaionji/chocopkgs#25]
I think we are going to need a DCH version of the 'nvidia-display-driver' package.

The current 'nvidia-display-driver' package in a clean install of Windows 10 1903 with a nVidia 2080 Ti throws an exit error of -467664896. Tried installing the drivers by hand and the installer said I had the "wrong version of windows".

Downloaded the DCH version of the drivers and they installed with no issue.

**Comment by AeliusSaionji** [comment]
I've since added DCH, thanks
