### ISSUE TITLE
goggalaxy: install isn't silent

### ISSUE THREAD

**Issue by jack1142** [AeliusSaionji/chocopkgs#32]
As in title, when I was updating from goggalaxy v2.0.15.43 to 2.0.20.38, graphical installer showed and I had to manually go through install.

**Comment by koolhand** [comment]
I had the same issue, with the same versions.

**Comment by AeliusSaionji** [comment]
Yeah seems like gog switched over to a custom webupdater that downloads the latest version whenever you run it.
And it doesn't support silent install.
I sent them a bug report about it, hopefully they'll fix it.

**Comment by AeliusSaionji** [comment]
(fixed a while back)
