### ISSUE TITLE
Installs incorrect version of Nvidia display drivers

### ISSUE THREAD

**Issue by MartyGentillon** [AeliusSaionji/chocopkgs#37]
The update to 496.13 still downloads 472.12

**Comment by AeliusSaionji** [comment]
Even now, the traditional win7 compatible driver is still a version behind. I can't update you to what doesn't exist yet.

If you're on Win10, the logical fix is for users to transition to the DCH driver- which all Win0 users should be on anyway. I might have to revive the win7 specific chocolatey package..... annoying. I'd rather not.

I'll have to change the chocolatey package to start pushing DCH on win10 users. In the past you needed to DDU the standard driver before DCH would take, though... not sure if that's still the case. If you're a win10 user who hasn't made the switch to DCH yet, could manually run the DCH driver installer and tell me what happens?

**Comment by kwilliams1987** [comment]
This is still an issue 6 months later. :-/
