### ISSUE TITLE
obs-studio package updated but install/portable didn't

### ISSUE THREAD

**Issue by flcdrg** [AeliusSaionji/chocopkgs#40]
version 27.2.0

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I think this is because the release tags specify version [27.2.0](https://github.com/obsproject/obs-studio/releases/tag/27.2.0), but installers use numbering as "*.*".

**Comment by AeliusSaionji** [comment]
This might be a problem with chocolatey servers.... my update scripts are working, but I'm getting the dreaded `Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.`

**Comment by AeliusSaionji** [comment]
https://github.com/chocolatey/home/issues/82

**Comment by flcdrg** [comment]
I suspect the package is too large (see comments I added on linked issue).

If that's the case you might need to change it to not embed the binaries.

**Comment by AeliusSaionji** [comment]
that is _incredibly_ inconvenient 😩

**Comment by AeliusSaionji** [comment]
I manually pushed these packages in x64 only, but I'll leave this issue open.

I didn't alter my automatic update script yet- optimistically hoping chocolatey will find an easy way to bump the filesize before the next obs update.

If not, I'll be hearing from y'all again 😄

**Comment by flcdrg** [comment]
Do you want a PR to switch to non-embedded? I can probably put one together if that helps.

the 200MB limit has been in place for a long time. Would be nice to see it increased, but I wouldn't hold my breath.

**Comment by overag3** [comment]
same problem with version 27.2.1

**Comment by DragRedSim** [comment]
And once again on 27.2.3. Per https://github.com/chocolatey/home/issues/59#issuecomment-1051054323 it sounds like it's not going to be raised any time soon, so moving to non-embedded is probably the best course of action for the time being. If @flcdrg is still willing, that would probably be appreciated.

**Comment by AeliusSaionji** [comment]
OBS dropped 32bit support so we're in the clear, for now 🤪
