### ISSUE TITLE
(mpv) Old files left behind after package upgrade

### ISSUE THREAD

**Issue by opusforlife2** [AeliusSaionji/chocopkgs#42]
Hi. Some files from previous versions are lying around in the `lib > mpv.install` folder, like:

```
mpv-0.32.0-x86_64.7z.txt
mpv-0.33.0-x86_64.7z.txt
```

and so on. Is it possible to ensure these are deleted when the package is upgraded?

**Comment by AeliusSaionji** [comment]
Pretty sure this is just something chocolatey is doing. I imagine they'll clear out if you uninstall then install mpv.

Are these files causing problems?

**Comment by opusforlife2** [comment]
No problems, just clutter.

If I keep mpv installed, they'll just keep piling up, won't they? In my view, the upgrade process should include cleanup like this.
