### ISSUE TITLE
mpv outdated

### ISSUE THREAD

**Issue by Technetium1** [AeliusSaionji/chocopkgs#43]
New release: https://github.com/mpv-player/mpv/releases/tag/v0.34.1

**Comment by AeliusSaionji** [comment]
Gotta bug shinchiro to make a binary https://sourceforge.net/projects/mpv-player-windows/files/release/

**Comment by Technetium1** [comment]
In that case... @shinchiro I'm not sure if I should open an issue at https://github.com/shinchiro/mpv-winbuild-cmake next time, or if there's not a repo for those builds on GitHub.

**Comment by SAJewers** [comment]
Looks like a build has been made now: https://github.com/shinchiro/mpv-winbuild-cmake/releases/tag/20221011

**Comment by AeliusSaionji** [comment]
Unfortunately it looks like these are still just automated nightly builds, which were previously located on sourceforge.

None of these are actually the January 3rd 2022 mpv release commit [349e437466163cb52f7d0aa227d4606edd9db501](https://github.com/mpv-player/mpv/commit/349e437466163cb52f7d0aa227d4606edd9db501)

I can't really submit an arbitrary build :/

**Comment by soredake** [comment]
https://sourceforge.net/projects/mpv-player-windows/files/release/

**Comment by AeliusSaionji** [comment]
submitted, thanks
