### ISSUE TITLE
wsltty outdated in chocolatey (but not in this repo)

### ISSUE THREAD

**Issue by slycordinator** [AeliusSaionji/chocopkgs#64]
In this repo, wsltty has been updated to 3.7.0.2

But in chocolatey, the latest version available is 3.6.4

It would be nice if the newer version were pushed to chocolatey.

Thanks

**Comment by AeliusSaionji** [comment]
The automation is working, chocotaley just rejects packages based on virustotal's false positives. Nothing I can do.
