### ISSUE TITLE
(mpv) mpv 2023.12.10 / v0.37.0 -> 2024.04.17 / v0.38.0

### ISSUE THREAD

**Issue by zWhdmB5T** [AeliusSaionji/chocopkgs#70]
- [Package Page](https://community.chocolatey.org/packages/mpv)
- [Package Source](https://github.com/AeliusSaionji/chocopkgs/tree/master/mpv)
- [Release Details](https://github.com/mpv-player/mpv/releases/tag/v0.38.0)
- [Installation](https://mpv.io/installation/)

**Comment by AeliusSaionji** [comment]
https://github.com/AeliusSaionji/chocopkgs/issues/74#issuecomment-2375832400
