### ISSUE TITLE
🛑 `advanced-renamer` can't be updated from Chocolatey since April 26

### ISSUE THREAD

**Issue by iki** [AeliusSaionji/chocopkgs#71]
🛑 `advanced-renamer` can't be updated from Chocolatey since April 26

🛑 The package for `advanced-renamer` is `3.95.4` in the [package source](https://github.com/AeliusSaionji/chocopkgs/blob/master/advanced-renamer/advanced-renamer.nuspec), **but** `3.94.3` in [Chocolatey Packages](https://community.chocolatey.org/packages/advanced-renamer) and in `choco search advanced-renamer`.

✔️ The package for `advanced-renamer.install` is at `3.95.4` in all the [package source](https://github.com/AeliusSaionji/chocopkgs/blob/master/advanced-renamer.install/advanced-renamer.install.nuspec) and [Chocolatey Packages](https://community.chocolatey.org/packages/advanced-renamer.install) and in `choco search advanced-renamer.install`.

As a result, since the last package source update, chocolatey lists `advanced-renamer.install` as available for update, but can't update it due to the fixed version dependency from old `advanced-renamer` in Chocolatey Packages.

Fresh installation install the older `3.94.3`.

**Comment by AeliusSaionji** [comment]
oh, did you get added as a maintainer? If so please remove me.

**Comment by tunisiano187** [comment]
Done.
