### ISSUE TITLE
(mpv) mpv 2023.12.10 / v0.37.0 -> mpvio v0.39.0 and remove the `PATH environment variable` and `file associations` from `mpv.install` automatically

### ISSUE THREAD

**Issue by candrapersada** [AeliusSaionji/chocopkgs#74]
* [Package Page](https://community.chocolatey.org/packages/mpv)
* [Package Source](https://github.com/AeliusSaionji/chocopkgs/tree/master/mpv)
* [Release Details](https://github.com/mpv-player/mpv/releases/tag/v0.39.0)
* [Installation](https://mpv.io/installation/)

**Comment by AeliusSaionji** [comment]
The person providing releases for Windows has not built the 0.39.0 release yet. See https://sourceforge.net/projects/mpv-player-windows/files/release/

When that does drop, let me know if the automated update script doesn't pick it up within a day or so.

As for chocolatey package mpv- I've formally axed it, please use mpvio from now on.

**Comment by candrapersada** [comment]
but why hasn't the link https://community.chocolatey.org/packages/mpv been deleted yet?

**Comment by candrapersada** [comment]
if updating mpv to mpvio automatically `PATH environment variable` and `file associations` change from mpv to mpvio.
